### PR TITLE
Improve collection lookup

### PR DESCRIPTION
**Pull request by ivansglazunov**
- [x] `mongo test-packages`

### CODE REVIEW

**Comment by dburles** [comment]
- [ ] Implement `ref` option
- [ ] No longer look up collections by `connection` ?
- [ ] Tests

**Comment by ivansglazunov** [comment]
If null-collection have ref, we can?
```js
new Mongo.Collection(null, { ref: 'test' });
Mongo.Collection.get('test'); // ok
// but
Mongo.Collection.get(null); // still work? or does not add to nullInstances?
```

**Comment by ivansglazunov** [comment]
You can go to my temp [c9](https://ide.c9.io/ivansglazunov/collection-instances) to see the process.

**Comment by dburles** [comment]
We should keep the same format as before when you call `getAll`.

**Comment by ivansglazunov** [comment]
Oh, my fault.

**Comment by ivansglazunov** [comment]
[tests](https://collection-instances-ivansglazunov.c9users.io/)

**Comment by ivansglazunov** [comment]
What are we waiting for? The delay on my part?

**Comment by dburles** [comment]
Yeah did you want to take care of the above items?

**Comment by ivansglazunov** [comment]
- [x] `ref`
- [ ] [connection](https://github.com/dburles/mongo-collection-instances/issues/31#issuecomment-194580996)
- [x] Tests
Already... ?

**Comment by ivansglazunov** [comment]
May be add to collections `_ref` value? Near `_name`.

**Comment by ivansglazunov** [comment]
This will be determined by what name it is possible refer to the collection if the collection itself if lost.

**Comment by ivansglazunov** [comment]
What else can I do?

**Comment by dburles** [comment]
Hey @ivansglazunov would you mind pushing so I can take a look?

**Comment by ivansglazunov** [comment]
Of course. I just thought that maybe have not made my part. What about suggestions about `_ref`?

**Comment by dburles** [comment]
I'm not sure why you would need to store it against the collection, what is your thinking on that?

**Comment by ivansglazunov** [comment]
[shuttler:ref](https://github.com/meteor-shuttle/ref) Adding `.Ref()` helper with link to collection by `_name`. If it null-collection, `_name` == `undefined`. How get collection ref for `Mongo.Collection.get` from collection?

**Comment by ivansglazunov** [comment]
https://github.com/meteor-shuttler/ref/blob/master/helper.js#L8

**Comment by dburles** [comment]
Hmm.. that seems to be unrelated. What I'm talking about is storing `ref` on the array of collections in order to use `Mongo.Collection.get` to look it up

**Comment by ivansglazunov** [comment]
Important point:
When you have already received the collection and should be written in a document of this collection ref. Now it is impossible to obtain. For this I propose to add `_ref`.

**Comment by dburles** [comment]
I think we should probably just stick with the performance improvement to the `get` method. I feel like these changes are too specific to a particular use-case that the majority of people won't ever need, and if that were the case, it's no great hurdle to just make use of collection-extensions and implement it in any way you like.

**Comment by ivansglazunov** [comment]
It's a pity. I would like to here was a functional. Universal namespace of collections. At least my team will use this. At a minimum, this functionality does not harm. However, i will have to make his own version of this library, if your version does not have these capabilities.

**Comment by ivansglazunov** [comment]
The problem is that it is impossible to implement this functionality in addition to that package in separate package. Either build this package or rebuild to other package.

**Comment by dburles** [comment]
The key is that there should be clear benefits to these extra features to anyone who uses the package (beyond just your team), if you can sell me on that I'll reconsider :)

**Comment by ivansglazunov** [comment]
It's an easy and beautiful to realize the link between multiple documents in different collections. These collections can be either local or remote. In the application can always be convenient to find on their by `ref`.It is not a question of opinion or sale. Previously, only the library worked with server collections, and it allows you to work with null-collections. Client collections can be a part of the logic associated overlapping documents in collections.
I remember about all the meteor half of my fellow developers say - it is not necessary for most programmers. Now they are on the meteor. Whom stops the fact that it now no one does not want some change? Better to imagine how it can be useful. **And I have the opposite opinion It will need most of the users.**

**Comment by ivansglazunov** [comment]
And how are you going to look for null collections without ref at all? Then it is better to cut out all the opportunity to look at him. Or add a search through all the options.
----
Personal...
And i'm afraid to think of what to call my version of `Mongo.Collection.get` to avoid naming conflicts....

**Comment by ivansglazunov** [comment]
It may be confusing your attribute in the collection? So do many of the library, for example [collection2](https://github.com/aldeed/meteor-collection2).

**Comment by ivansglazunov** [comment]
If there is a positive decision, and will be happy to supplement the documentation. :)

**Comment by dburles** [comment]
Sounds like you're building something a bit different overall to what the core of this package provides, I think it makes sense for you to build it yourself. I don't see any need to mimic the same name and API as here though if it's providing a different feature set.

**Comment by ivansglazunov** [comment]
The task is one and the same. Namespace for collections.

**Comment by dburles** [comment]
Remember the typical use case that I've seen with this package is for usually for some kind of admin interface or low-level tool where they require the ability to show a list of collections. What's the use-case(s) for the extra features you're asking for? You say most people will have a use for them, but why? That's what I'm interested in.

**Comment by ivansglazunov** [comment]
So there are two options:
* Cut support null-collections completely.
* Provide this support.

**Comment by ivansglazunov** [comment]
It is not a question of my projects or applications. It is only a matter of null-collections.
Without `ref` possibility of their support is virtually nonexistent.
I can make the package `mongo-collection-null-instances` extends` Mongo.Colleciton.get` and `Mongo.Collection.getAll` and adding a separate array` nullInstances`. Then this package can be completely cut out these possibilities.

**Comment by ivansglazunov** [comment]
And a separate package `mongo-collection-instances-ref` add field `_ref`.

**Comment by dburles** [comment]
Okay, so null collections are not currently supported, that we both agree on, but as I said earlier I have never seen an issue pop up relating to this being a problem and therefore solving a problem that doesn't exist is never a great idea.

You seem to have a requirement to have the ability to reference null collections, but you still haven't explained the practical reason why that would be useful. The reason why I ask is that I've never had the need to grab the collection based on document fetched from it, and I've worked on a lot of Meteor applications!

**Comment by ivansglazunov** [comment]
As an example:Unload from the server 2-5 server collections of several hundred documents. Edit them, without synchronization. Save thereafter.
Keep the history of changes in real time, but not on the server.
When you create a game with only 25 collections storage ai. Some of them are virtual and are calculated based on the client server.
Within these client collections so the same is necessary to refer to each other.
It is not difficult to think up examples for simple sites stores.

---

I do not mind divide that on several packages, in principle, already have an understanding of how to do it. This way you think is correct?

**Comment by ivansglazunov** [comment]
In any case, thanks for improved performance. ;)

**Comment by dburles** [comment]
Really this is such a simple package (especially now since it's using collection-extensions) that I feel like if you run into a requirement like yourself, it's simple enough for anyone to hack together their own version of it specific to their application and then just use that instead.

Though if you were to publish your own version, since the features would be different it would make sense to publish under a different name as to not confuse people with regards to their function. I'd just place all of the functionality within the `shuttler:ref` package.

The performance improvement PR makes sense, I'll look into getting that merged soon, thanks!

**Comment by ivansglazunov** [comment]
Yeah, I guess you're right. You do not need to create too wrappers. Thank you!

**Pull request closed without merging**
